n1 = str(input("1° Tarefa: "))
n2 = str(input("2° Tarefa: "))
n3 = str(input("3° Tarefa: "))
n4 = str(input("4° Tarefa: "))
n5 = str(input("5° Tarefa: "))
n6 = str(input("6° Tarefa: "))
n7 = str(input("7° Tarefa: "))
n8 = str(input("8° Tarefa: "))
n9 = str(input("9° Tarefa: "))
n10 = str(input("10° Tarefa: "))

print("1°tarefa: ", n1)
print("2°tarefa: ", n2)
print("3°tarefa: ", n3)
print("4°tarefa: ", n4)
print("5°tarefa: ", n5)
print("6°tarefa: ", n6)
print("7°tarefa: ", n7)
print("8°tarefa: ", n8)
print("9°tarefa: ", n9)
print("10°tarefa: ", n10)
